version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-xray"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bahfqkp69dl9"
s3_prefix = "sam-xray"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
